USE qveo;
/*Pais*/
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('EE.UU');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Reino Unido');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Canadá');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Alemania');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Sudáfrica');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Israel');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Australia');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Suecia');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Francia');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Japón');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Irlanda');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Italia');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('Bélgica');
INSERT INTO `qveo`.`pais` (`NOMBRE`) VALUES ('España');

/**Genero*/
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Animación');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Comedia');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Fantasía');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Infantil');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Aventura');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Acción');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Zombies');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Ciencia ficción');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Terror');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Suspenso');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Misterio');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Crimen');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Drama');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Biográfica');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Superhéroes');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Terror');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Histórico');
INSERT INTO `qveo`.`genero` (`NOMBRE`) VALUES ('Romance');

/**Director*/
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Eric Darnell');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Tom McGrath');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Dean DeBlois');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Chris Sanders');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Marc Forster');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ( 'Nima Nourizadeh');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Renny Harlin');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Gareth Edwards');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Steven Spielberg');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('John Francis Daley');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Jonathan Goldstein');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Clint Eastwood');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Christopher Nolan');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Sam Raimi');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('James DeMonaco');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Peter Jackson');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('David Petrarca');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Jeff Myers');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Michael Hirst');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Joe Carnahan');
INSERT INTO `qveo`.`director` ( `NOMBRE`) VALUES ('Otto Bathurst');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Dan Harmon');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('David Crane');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Marc Vigil');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Bill Dubuque');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Michael Seitzman');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Bill Dubuque');
INSERT INTO `qveo`.`director` (`NOMBRE`) VALUES ('Michael Seitzman');

/**Actor*/
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Ben Stiller','H','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Chris Rock','H','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('David Schwimmer','H','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jada Pinkett','M','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Cedric Antonio Kyles','M','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Andy Richter','H','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Bernie Mac','H','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Alec Baldwin','H','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Sherri Shepherd','M','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('William James Adams','H','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('John DiMaggio','H','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Conrad Vernon','H','1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Sacha Baron Cohen','M','2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jay Baruchel', 'H', '3');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Gerard Butler', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('América Ferrera', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Kristen Wiig', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jonah Hill', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Todd Joseph Miller', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Christopher Mintz-Plasse', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Craig Ferguson', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('William Bradley Pitt', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Mireille Enos', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Fana Mokoena', 'H', '5');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Daniella Kertesz', 'M', '6');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('James Badge Dale', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Thomas Mann', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Oliver Cooper', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jonathan Daniel Brown', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Thomas Jane', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Saffron Dominique Burrows ', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jacqueline Susan McKenzie', 'M', '7');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Stellan John Skarsgård ', 'H', '8');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Samuel L. Jackson', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('James Todd Smith III', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Michael David Rapaport', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES  ('Aaron Johnson', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Ken Watanabe', 'H', '10');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Elizabeth Olsen', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Juliette Binoche', 'M', '9');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Sally Hawkins', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('David Strathairn', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Bryan Cranston', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Tye Sheridan', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Olivia Cooke', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Ben Mendelsohn', 'H', '7');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Hannah John-Kamen', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Simon Pegg', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Mark Rylance', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Rachel Anne McAdams', 'M', '3');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Billy Magnussen', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Kylie Bunbury', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jesse Plemons', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Michael C. Hall', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Kyle Chandler', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jason Bateman', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Sharon Horgan', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Lamorne Morris', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Bradley Cooper', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Sienna Miller', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Leonardo DiCaprio', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Ellen Page', 'M', '3');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Marion Cotillard', 'M', '9');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Joseph Gordon-Levitt', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Tom Hardy', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Cillian Murphy', 'H', '11');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Michael Caine', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Tobey Maguire', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Willem Dafoe', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Kirsten Dunst', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('James Franco', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Cliff Robertson', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Rosemary Harris', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jonathan Kimble Simmons', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Frank Grillo', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Elizabeth Mitchell', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Mykelti Williamson', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Ian McKellen', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Martin Freeman', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Richard Armitage', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Benedict Cumberbatch', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Tom Cullen', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jim Carter', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Pádraic Delaney', 'H', '11');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Simon Merrells', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Justin Roiland', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Spencer Grammer', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Sarah Chalke', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Chris Parnell', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Travis Fimmel', 'H', '7');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Katheryn Winnick', 'M', '3');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Clive Standen', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jessalyn Gilsig', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('James Spader', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Megan Boone', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Diego Klattenhoff', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Ryan Eggold', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Helen McCrory', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Paul Anderson', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Sophie Rundle', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Joel McHale', 'H', '3');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('John Oliver', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Chevy Chase', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jennifer Aniston', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Courteney Cox', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Lisa Kudrow', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Matt LeBlanc', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Matthew Perry', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Jim Parsons', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Melissa Rauch', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Kaley Cuoco', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Johnny Galecki', 'H', '14');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Kunal Nayar', 'H', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Simon Helberg', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Mayim Bialik', 'H', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Rodolfo Sancho', 'H', '14');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Aura Garrido', 'M', '14');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Nacho Fresneda', 'H', '14');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Cayetana Guillén Cuervo', 'H', '14');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Julia Garner', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Laura Linney', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Sofia Hublitz', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Melanie Chandra', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Bonnie Somerville', 'M', '1');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Raza Jaffrey', 'M', '2');
INSERT INTO `qveo`.`actor` (`NOMBRE`, `SEXO`, `ID_PAIS`) VALUES ('Marcia Gay Harden', 'M', '1');


/**Pelicula*/
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Madagascar', '01:26:00', 'Mark Burton', 'Cuatro animales muy mimados del zoo de Nueva York naufragan en la isla de Madagascar y deben aprender a sobrevivir en un mundo salvaje.', '2005-07-17', '1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Cómo entrenar a tu dragón ','01:38:00','Dean DeBlois','Hipo, un vikingo adolescente, comienza las clases de entrenamiento con dragones y ve por fin una oportunidad para demostrar que es capaz de convertirse en guerrero cuando hace amistad con un dragón herido.','2010-03-26','1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Guerra mundial Z ', '01:55:00', 'Damon Lindelof', 'Cuando una pandemia de zombis amenaza con destruir a la humanidad, un exinvestigador de Naciones Unidas es obligado a regresar al servicio para intentar descubrir la fuente de la infección.', '2013-06-21', '1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Project X', '01:28:00', 'Matt Drake', 'Tres estudiantes de secundaria deciden organizar una fiesta salvaje en casa de uno de ellos.Sin embargo, una serie de complicaciones imprevistas harán que la fiesta se descontrole.', '2012-03-02', '1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Deep Blue Sea', '01:45:00', 'Duncan Kennedy', 'Una bióloga marina trata de encontrar la clave de la regeneración de los tejidos del cerebro humano que modifica el ADN de unos tiburones y los convierte en monstruos depredadores que pondrán en peligro a todo el equipo.', '1999-07-28', '1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Godzilla (película de 2014)', '02:03:00', 'Max Borenstein', 'Godzilla, Rey de los Monstruos, surge para combatir a enemigos enormes y malos que se han estado alimentando con los reactores de una planta nuclear y ahora amenazan a la humanidad con aniquilarla.', '2014-05-16', '10');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Ready Player One', '02:20:00', 'Donald De Line', 'El adolescente Wade Watts es solo una de las millones de personas que se evaden del sombrío mundo real para sumergirse en un mundo utópico virtual donde todo es posible: OASIS. Wade participa en la búsqueda del tesoro que el creador de este mundo imaginario dejó oculto en su obra. No obstante, hay gente muy peligrosa compitiendo contra él.', '2018-03-20', '1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Noche de juegos', '01:40:00', 'Mark Perez', 'Un grupo de amigos que se reúne una vez a la semana para jugar cambia su rutina y decide resolver un falso asesinato, pero, a medida que la partida avanza, se dan cuenta de que esta vez lo que está ocurriendo es real.', '2018-02-23', '1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('El francotirador', '02:12:00', 'Jason Dean Hall', 'El francotirador y SEAL de la Armada estadounidense Chris Kyle salva muchas vidas en los campos de batalla en Irak mientras se esfuerza por ser un buen marido y padre con sus seres queridos de regreso en Estados Unidos.', '2014-12-25', '1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Origen', '02:28:00', 'Christopher Nolan', 'La misión, llamada “inserción”, consiste en implantar el origen de una idea o concepto en la mente de su cliente rival para que la interprete como propia. Así, Dom Cobb reúne a un grupo de especialistas que viajará por la mente de su presa, Robert Fischer Jr.', '2010-08-06', '1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Spider-Man', '02:02:00', 'David Koepp', 'Un tímido estudiante se vuelve en un luchador contra el crimen, desde que la picadura de una araña mutante le da poderes extraordinarios.', '2002-06-24', '1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('Election: La noche de las bestias', '01:49:00', 'James DeMonaco', 'Hace 18 años, Charlie Roan presenció el asesinato de su familia durante la noche de la Purga. En el presente, Charlie es candidata a la presidencia y quiere acabar con el régimen impuesto hace 20 años, que utiliza este día para eliminar a los más pobres y recortar el gasto público, pero antes deberá sobrevivir a doce horas de terror absoluto.', '2016-07-01', '1');
INSERT INTO `qveo`.`pelicula` (`TITULO`, `DURACION`, `GUION`, `SINOPSIS`, `ANIO`, `ID_PAIS`) VALUES ('El hobbit: la desolación de Smaug', '02:41:00', 'Fran Walsh', 'Bilbo y sus compañeros continúan su viaje hacia el este y enfrentan muchos peligros de camino a la Montaña Solitaria. Su recorrido culmina con un encuentro con el temible dragón Smaug.', '2013-12-13', '1');

/**Plataforma*/
INSERT INTO `qveo`.`plataforma` (`NOMBRE`) VALUES ('HBO');
INSERT INTO `qveo`.`plataforma` (`NOMBRE`) VALUES ('Netflix');
INSERT INTO `qveo`.`plataforma` (`NOMBRE`) VALUES ('Amazon Prime');
INSERT INTO `qveo`.`plataforma` (`NOMBRE`) VALUES ('Disney Plus');
INSERT INTO `qveo`.`plataforma` (`NOMBRE`) VALUES ('Filmin');
INSERT INTO `qveo`.`plataforma` (`NOMBRE`) VALUES ('Movistar');

/**Serie */
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('Knightfall', '2017-12-06', 'Los Templarios dedicaron su vida a cuidar del Santo Grial. Knightfall es un drama histórico que recrea las cruzadas y la vida de esta hermandad, una mirada a los últimos días de los Caballeros Templarios durante el siglo XIV.', '1', '10', '1');
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('Rick and Morty', '2013-12-02', 'Rick & Morty relata las aventuras de un científico loco, mal encarado y alcohólico que vive en casa de su hija, Beth, junto a Jerry, el marido de ésta y los dos hijos de la pareja, Summer y Morty, compañero de su abuelo en sus andanzas.', '4', '41', '1');
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('Vikingos', '2013-03-02', 'Narra las aventuras del héroe Ragnar Lothbrok, de sus hermanos vikingos y su familia, cuando él se subleva para convertirse en el rey de las tribus vikingas. Además de ser un guerrero valiente, Ragnar encarna las tradiciones nórdicas de la devoción a los dioses. Según la leyenda era descendiente directo del dios Odín', '6', '79', '2');
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('The Blacklist', '2013-09-23', 'Durante décadas, el ex agente de gobierno Raymond \'Red\' Reddington (James Spader) ha sido uno de los fugitivos más buscados por el FBI. Tras esto, decide hacer al FBI una oferta un tanto enigmática: ayudar a atrapar al desaparecido terrorista Ranko Zamani, bajo la condición de hablar sólo con la agente Elisabeth Keen.', '7', '146', '1');
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('Peaky Blinders', '2013-09-12', 'Las actividades del ambicioso jefe de la banda, Thomas Shelby (Cillian Murphy), llaman la atención del Inspector jefe Chester Campbell, un detective de la Real Policía Irlandesa que es enviado desde Belfast para limpiar la ciudad y encontrar el cargamento de armas que fue robado de la fábrica local.', '5', '30', '2');
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('Community', '2009-09-17', 'Community es una comedia televisiva estadounidense creada por Dan Harmon y emitida por NBC y Yahoo!, que trata sobre un grupo de estudiantes que asisten a una universidad comunitaria situada en la ciudad ficticia de Greendale, Colorado.', '6', '110', '1');
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('Friends', '1994-09-22', 'Friends nos contaba las peripecias de un grupo de amigos que viven en Manhattan (Nueva York), ellos eran Monica Geller, su hermano Ross Geller, Rachel Green una amiga de la infancia, sus vecinos Chandler Bing y Joey Tribbiani y otra amiga, Phoebe Buffay.', '10', '236', '1');
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('The Big Bang Theory ', '2007-09-24', 'La serie comienza con la llegada de Penny, aspirante a actriz, al apartamento vecino del que comparten Sheldon y Leonard, dos físicos que trabajan en el Instituto Tecnológico de California (Caltech). Leonard se enamora desde el primer momento de Penny.', '12', '279', '1');
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('El Ministerio del Tiempo', '2015-02-24', 'El Ministerio del Tiempo es una institución gubernamental secreta que depende directamente de la Presidencia del Gobierno español. Solo monarcas, presidentes y un número exclusivo de personas saben de él. El paso hacia otras épocas se realiza a través de puertas vigiladas por las patrullas del ministerio.', '3', '34', '14');
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('Ozark', '2017-07-21', 'La historia gira en torno a la familia Byrde, formada por el matrimonio de Marty y Wendy y sus dos hijos adolescentes, Charlotte y Jonah. ... Los Byrde se verán envueltos en el mundo clandestino del blanqueo de dinero ilegal para un cártel de drogas mexicano.', '3', '30', '1');
INSERT INTO `qveo`.`serie` (`TITULO`, `FECHA_INICIO`, `SINOPSIS`, `TEMPORADAS`, `CAPITULOS`, `ID_PAIS`) VALUES ('Código Negro', '2015-09-30', 'Basada en un documental de Ryan McGarry, Code Black es un drama médico que tiene lugar en la sala de emergencias más conocida del país, donde la cantidad de pacientes es mucho mayor que los medios y recursos con los que cuentan los sanitarios.', '3', '47', '1');

/**Actor_Pelicula*/
insert into `qveo`.`actor_pelicula` values(1,1);
insert into `qveo`.`actor_pelicula` values(2,1);
insert into `qveo`.`actor_pelicula` values(3,1);
insert into `qveo`.`actor_pelicula` values(4,1);
insert into `qveo`.`actor_pelicula` values(4,1);
insert into `qveo`.`actor_pelicula` values(5,1);
insert into `qveo`.`actor_pelicula` values(6,1);
insert into `qveo`.`actor_pelicula` values(7,1);
insert into `qveo`.`actor_pelicula` values(8,1);
insert into `qveo`.`actor_pelicula` values(9,1);
insert into `qveo`.`actor_pelicula` values(10,1);
insert into `qveo`.`actor_pelicula` values(11,1);
insert into `qveo`.`actor_pelicula` values(12,1);
insert into `qveo`.`actor_pelicula` values(13,1);
insert into `qveo`.`actor_pelicula` values(14,2);
insert into `qveo`.`actor_pelicula` values(15,2);
insert into `qveo`.`actor_pelicula` values(16,2);
insert into `qveo`.`actor_pelicula` values(17,2);
insert into `qveo`.`actor_pelicula` values(18,2);
insert into `qveo`.`actor_pelicula` values(19,2);
insert into `qveo`.`actor_pelicula` values(20,2);
insert into `qveo`.`actor_pelicula` values(21,2);
insert into `qveo`.`actor_pelicula` values(22,3);
insert into `qveo`.`actor_pelicula` values(23,3);
insert into `qveo`.`actor_pelicula` values(24,3);
insert into `qveo`.`actor_pelicula` values(25,3);
insert into `qveo`.`actor_pelicula` values(26,3);
insert into `qveo`.`actor_pelicula` values(27,4);
insert into `qveo`.`actor_pelicula` values(28,4);
insert into `qveo`.`actor_pelicula` values(29,4);
insert into `qveo`.`actor_pelicula` values(30,5);
insert into `qveo`.`actor_pelicula` values(31,5);
insert into `qveo`.`actor_pelicula` values(32,5);
insert into `qveo`.`actor_pelicula` values(33,5);
insert into `qveo`.`actor_pelicula` values(34,5);
insert into `qveo`.`actor_pelicula` values(35,5);
insert into `qveo`.`actor_pelicula` values(36,5);
insert into `qveo`.`actor_pelicula` values(37,6);
insert into `qveo`.`actor_pelicula` values(38,6);
insert into `qveo`.`actor_pelicula` values(39,6);
insert into `qveo`.`actor_pelicula` values(40,6);
insert into `qveo`.`actor_pelicula` values(41,6);
insert into `qveo`.`actor_pelicula` values(42,6);
insert into `qveo`.`actor_pelicula` values(43,6);
insert into `qveo`.`actor_pelicula` values(19,7);
insert into `qveo`.`actor_pelicula` values(44,7);
insert into `qveo`.`actor_pelicula` values(45,7);
insert into `qveo`.`actor_pelicula` values(46,7);
insert into `qveo`.`actor_pelicula` values(47,7);
insert into `qveo`.`actor_pelicula` values(48,7);
insert into `qveo`.`actor_pelicula` values(49,7);
insert into `qveo`.`actor_pelicula` values(50,8);
insert into `qveo`.`actor_pelicula` values(51,8);
insert into `qveo`.`actor_pelicula` values(52,8);
insert into `qveo`.`actor_pelicula` values(53,8);
insert into `qveo`.`actor_pelicula` values(54,8);
insert into `qveo`.`actor_pelicula` values(55,8);
insert into `qveo`.`actor_pelicula` values(56,8);
insert into `qveo`.`actor_pelicula` values(57,8);
insert into `qveo`.`actor_pelicula` values(58,8);
insert into `qveo`.`actor_pelicula` values(59,9);
insert into `qveo`.`actor_pelicula` values(60,9);
insert into `qveo`.`actor_pelicula` values(61,10);
insert into `qveo`.`actor_pelicula` values(62,10);
insert into `qveo`.`actor_pelicula` values(63,10);
insert into `qveo`.`actor_pelicula` values(64,10);
insert into `qveo`.`actor_pelicula` values(65,10);
insert into `qveo`.`actor_pelicula` values(66,10);
insert into `qveo`.`actor_pelicula` values(67,10);
insert into `qveo`.`actor_pelicula` values(38,10);
insert into `qveo`.`actor_pelicula` values(68,11);
insert into `qveo`.`actor_pelicula` values(69,11);
insert into `qveo`.`actor_pelicula` values(70,11);
insert into `qveo`.`actor_pelicula` values(71,11);
insert into `qveo`.`actor_pelicula` values(72,11);
insert into `qveo`.`actor_pelicula` values(73,11);
insert into `qveo`.`actor_pelicula` values(74,11);
insert into `qveo`.`actor_pelicula` values(75,12);
insert into `qveo`.`actor_pelicula` values(76,12);
insert into `qveo`.`actor_pelicula` values(77,12);
insert into `qveo`.`actor_pelicula` values(78,13);
insert into `qveo`.`actor_pelicula` values(79,13);
insert into `qveo`.`actor_pelicula` values(80,13);
insert into `qveo`.`actor_pelicula` values(81,13);

/**genero_pelicula*/
insert into `qveo`.`genero_pelicula` values(1,1);
insert into `qveo`.`genero_pelicula` values(2,1);
insert into `qveo`.`genero_pelicula` values(1,2);
insert into `qveo`.`genero_pelicula` values(3,2);
insert into `qveo`.`genero_pelicula` values(4,2);
insert into `qveo`.`genero_pelicula` values(5,2);
insert into `qveo`.`genero_pelicula` values(6,3);
insert into `qveo`.`genero_pelicula` values(7,3);
insert into `qveo`.`genero_pelicula` values(2,4);
insert into `qveo`.`genero_pelicula` values(8,5);
insert into `qveo`.`genero_pelicula` values(9,5);
insert into `qveo`.`genero_pelicula` values(10,5);
insert into `qveo`.`genero_pelicula` values(8,6);
insert into `qveo`.`genero_pelicula` values(6,6);
insert into `qveo`.`genero_pelicula` values(8,7);
insert into `qveo`.`genero_pelicula` values(6,7);
insert into `qveo`.`genero_pelicula` values(5,7);
insert into `qveo`.`genero_pelicula` values(5,8);
insert into `qveo`.`genero_pelicula` values(6,8);
insert into `qveo`.`genero_pelicula` values(10,8);
insert into `qveo`.`genero_pelicula` values(11,8);
insert into `qveo`.`genero_pelicula` values(12,8);
insert into `qveo`.`genero_pelicula` values(13,9);
insert into `qveo`.`genero_pelicula` values(14,9);
insert into `qveo`.`genero_pelicula` values(6,10);
insert into `qveo`.`genero_pelicula` values(8,10);
insert into `qveo`.`genero_pelicula` values(10,10);
insert into `qveo`.`genero_pelicula` values(13,10);
insert into `qveo`.`genero_pelicula` values(6,11);
insert into `qveo`.`genero_pelicula` values(8,11);
insert into `qveo`.`genero_pelicula` values(13,11);
insert into `qveo`.`genero_pelicula` values(15,11);
insert into `qveo`.`genero_pelicula` values(9,12);
insert into `qveo`.`genero_pelicula` values(3,13);
insert into `qveo`.`genero_pelicula` values(5,13);
insert into `qveo`.`genero_pelicula` values(6,13);

/**Pelicula_plataforma*/
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (1,1);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (1,2);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (2,1);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (2,2);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (3,1);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (3,2);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (4,2);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (4,3);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (5,2);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (5,3);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (6,2);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (6,3);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (7,1);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (7,3);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (8,1);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (8,3);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (9,1);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (9,3);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (10,1);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (10,2);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (10,3);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (11,1);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (12,2);
insert into `qveo`.`pelicula_plataforma` (`ID_PELICULA`, `ID_PLATAFORMA`) values (13,3);

/**Pelicula_Director*/
insert into `qveo`.`pelicula_director` values (1,1);
insert into `qveo`.`pelicula_director` values (1,2);
insert into `qveo`.`pelicula_director` values (2,3);
insert into `qveo`.`pelicula_director` values (2,4);
insert into `qveo`.`pelicula_director` values (3,5);
insert into `qveo`.`pelicula_director` values (4,6);
insert into `qveo`.`pelicula_director` values (5,7);
insert into `qveo`.`pelicula_director` values (6,8);
insert into `qveo`.`pelicula_director` values (7,9);
insert into `qveo`.`pelicula_director` values (8,10);
insert into `qveo`.`pelicula_director` values (8,11);
insert into `qveo`.`pelicula_director` values (9,12);
insert into `qveo`.`pelicula_director` values (10,13);
insert into `qveo`.`pelicula_director` values (11,14);
insert into `qveo`.`pelicula_director` values (12,15);
insert into `qveo`.`pelicula_director` values (13,17);

/**Actor_Serie*/
insert into `qveo`.`actor_serie` values(83,1);
insert into `qveo`.`actor_serie` values(84,1);
insert into `qveo`.`actor_serie` values(85,1);
insert into `qveo`.`actor_serie` values(86,2);
insert into `qveo`.`actor_serie` values(87,2);
insert into `qveo`.`actor_serie` values(88,2);
insert into `qveo`.`actor_serie` values(89,2);
insert into `qveo`.`actor_serie` values(90,3);
insert into `qveo`.`actor_serie` values(91,3);
insert into `qveo`.`actor_serie` values(92,3);
insert into `qveo`.`actor_serie` values(93,3);
insert into `qveo`.`actor_serie` values(94,4);
insert into `qveo`.`actor_serie` values(95,4);
insert into `qveo`.`actor_serie` values(96,4);
insert into `qveo`.`actor_serie` values(97,4);
insert into `qveo`.`actor_serie` values(98,5);
insert into `qveo`.`actor_serie` values(99,5);
insert into `qveo`.`actor_serie` values(100,5);
insert into `qveo`.`actor_serie` values(66,5);
insert into `qveo`.`actor_serie` values(101,6);
insert into `qveo`.`actor_serie` values(102,6);
insert into `qveo`.`actor_serie` values(103,6);
insert into `qveo`.`actor_serie` values(3,7);
insert into `qveo`.`actor_serie` values(104,7);
insert into `qveo`.`actor_serie` values(105,7);
insert into `qveo`.`actor_serie` values(106,7);
insert into `qveo`.`actor_serie` values(107,7);
insert into `qveo`.`actor_serie` values(108,7);
insert into `qveo`.`actor_serie` values(109,8);
insert into `qveo`.`actor_serie` values(110,8);
insert into `qveo`.`actor_serie` values(111,8);
insert into `qveo`.`actor_serie` values(112,8);
insert into `qveo`.`actor_serie` values(113,8);
insert into `qveo`.`actor_serie` values(114,8);
insert into `qveo`.`actor_serie` values(115,8);
insert into `qveo`.`actor_serie` values(116,9);
insert into `qveo`.`actor_serie` values(117,9);
insert into `qveo`.`actor_serie` values(118,9);
insert into `qveo`.`actor_serie` values(119,9);
insert into `qveo`.`actor_serie` values(56,10);
insert into `qveo`.`actor_serie` values(120,10);
insert into `qveo`.`actor_serie` values(121,10);
insert into `qveo`.`actor_serie` values(122,10);
insert into `qveo`.`actor_serie` values(123,11);
insert into `qveo`.`actor_serie` values(124,11);
insert into `qveo`.`actor_serie` values(125,11);
insert into `qveo`.`actor_serie` values(126,11);

/**Serie_Plataforma*/
insert into `qveo`.`serie_plataforma` values (1,1);
insert into `qveo`.`serie_plataforma` values (1,2);
insert into `qveo`.`serie_plataforma` values (2,1);
insert into `qveo`.`serie_plataforma` values (2,2);
insert into `qveo`.`serie_plataforma` values (3,1);
insert into `qveo`.`serie_plataforma` values (3,2);
insert into `qveo`.`serie_plataforma` values (4,2);
insert into `qveo`.`serie_plataforma` values (4,3);
insert into `qveo`.`serie_plataforma` values (5,2);
insert into `qveo`.`serie_plataforma` values (5,3);
insert into `qveo`.`serie_plataforma` values (6,2);
insert into `qveo`.`serie_plataforma` values (6,3);
insert into `qveo`.`serie_plataforma` values (7,1);
insert into `qveo`.`serie_plataforma` values (7,2);
insert into `qveo`.`serie_plataforma` values (7,3);
insert into `qveo`.`serie_plataforma` values (8,1);
insert into `qveo`.`serie_plataforma` values (8,2);
insert into `qveo`.`serie_plataforma` values (8,3);
insert into `qveo`.`serie_plataforma` values (9,1);
insert into `qveo`.`serie_plataforma` values (10,2);
insert into `qveo`.`serie_plataforma` values (11,3);

/**Genero_Serie*/
insert into `qveo`.`genero_serie` values(5,1);
insert into `qveo`.`genero_serie` values(6,1);
insert into `qveo`.`genero_serie` values(13,1);
insert into `qveo`.`genero_serie` values(17,1);
insert into `qveo`.`genero_serie` values(1,2);
insert into `qveo`.`genero_serie` values(2,2);
insert into `qveo`.`genero_serie` values(8,2);
insert into `qveo`.`genero_serie` values(6,3);
insert into `qveo`.`genero_serie` values(8,3);
insert into `qveo`.`genero_serie` values(13,3);
insert into `qveo`.`genero_serie` values(17,3);
insert into `qveo`.`genero_serie` values(5,4);
insert into `qveo`.`genero_serie` values(6,4);
insert into `qveo`.`genero_serie` values(8,4);
insert into `qveo`.`genero_serie` values(10,4);
insert into `qveo`.`genero_serie` values(11,4);
insert into `qveo`.`genero_serie` values(12,4);
insert into `qveo`.`genero_serie` values(13,4);
insert into `qveo`.`genero_serie` values(16,4);
insert into `qveo`.`genero_serie` values(17,4);
insert into `qveo`.`genero_serie` values(18,4);
insert into `qveo`.`genero_serie` values(12,5);
insert into `qveo`.`genero_serie` values(13,5);
insert into `qveo`.`genero_serie` values(2,6);
insert into `qveo`.`genero_serie` values(8,6);
insert into `qveo`.`genero_serie` values(2,7);
insert into `qveo`.`genero_serie` values(13,7);
insert into `qveo`.`genero_serie` values(18,7);
insert into `qveo`.`genero_serie` values(2,8);
insert into `qveo`.`genero_serie` values(18,8);
insert into `qveo`.`genero_serie` values(3,9);
insert into `qveo`.`genero_serie` values(5,9);
insert into `qveo`.`genero_serie` values(6,9);
insert into `qveo`.`genero_serie` values(8,9);
insert into `qveo`.`genero_serie` values(10,10);
insert into `qveo`.`genero_serie` values(11,10);
insert into `qveo`.`genero_serie` values(12,10);
insert into `qveo`.`genero_serie` values(13,10);
insert into `qveo`.`genero_serie` values(10,11);
insert into `qveo`.`genero_serie` values(11,11);
insert into `qveo`.`genero_serie` values(12,11);
insert into `qveo`.`genero_serie` values(13,11);

/**Director_Series*/
insert into `qveo`.`director_serie` values (1,18);
insert into `qveo`.`director_serie` values (2,19);
insert into `qveo`.`director_serie` values (3,20);
insert into `qveo`.`director_serie` values (4,21);
insert into `qveo`.`director_serie` values (5,22);
insert into `qveo`.`director_serie` values (6,23);
insert into `qveo`.`director_serie` values (7,24);
insert into `qveo`.`director_serie` values (8,25);
insert into `qveo`.`director_serie` values (9,26);
insert into `qveo`.`director_serie` values (10,27);
insert into `qveo`.`director_serie` values (11,28);
